# DataSourceConfig
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///mybatis_plus?userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 192.168.255.128
      port: 27017
      database: admin # 使用的数据库
      authentication-database: admin #登陆认证的逻辑库名
      username: root
      password: 123456
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除（0）